blank_issues_enabled: true
contact_links:
  - name: Openit Support
    url: https://t.me/yusteven
    about: 获得关于节点 / 订阅使用方面的支持 Telegram 24h人工客服💁‍♂️
  - name: ShareCentrePro Channel
    url: https://t.me/ShareCentrePro
    about: 想获取我们的最新消息？欢迎加入 Telegram 的 ShareCentrePro
  - name: ShareCentrePro Group
    url: https://t.me/woisx
    about: 想与志同道合的伙伴们交流一下( ͡° ͜ʖ ͡°)欢迎加入 Telegram 的 ShareCentre Pro || Chat
